"""empty message

Revision ID: c19f79fea453
Revises: 
Create Date: 2020-04-25 19:43:38.152813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c19f79fea453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('post_code', table_name='soil')
    op.drop_table('soil')
    op.add_column('city', sa.Column('ph_from', sa.Float(), nullable=True))
    op.add_column('city', sa.Column('ph_to', sa.Float(), nullable=True))
    op.alter_column('city', 'city_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('city', 'post_code',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.drop_index('city_name', table_name='city')
    op.drop_index('post_code', table_name='city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('post_code', 'city', ['post_code'], unique=True)
    op.create_index('city_name', 'city', ['city_name'], unique=True)
    op.alter_column('city', 'post_code',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.alter_column('city', 'city_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('city', 'ph_to')
    op.drop_column('city', 'ph_from')
    op.create_table('soil',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ph_value', mysql.FLOAT(), nullable=False),
    sa.Column('post_code', mysql.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('post_code', 'soil', ['post_code'], unique=True)
    # ### end Alembic commands ###
